### ISSUE TITLE
Get RPM data without installing

### ISSUE THREAD

**Issue by asamalik** [minimization/feedback-pipeline#4]
In the backend, the script first installs all bases and use cases into directories and then queries them to get the data it needs.

That's quite inefficient and takes a long time (but I knew how to do that!).

So we need to find a way to get the same data without the installation step. I'm sure it's possible and it might be even quite easy.

**Comment by asamalik** [comment]
I'm sure @ignatenkobrain will know the answer!

**Comment by ignatenkobrain** [comment]
Well, you can use the script I wrote :)

https://gist.github.com/ignatenkobrain/2ae6a21e112ad5ebd5b7ec87fe3e94ad

**Comment by asamalik** [comment]
@ignatenkobrain thanks for that!

I see it's using libsolv directly — would that work with modules, too? I used DNF in my implementation to make sure I get the same behaviour as when you actually install it in Fedora. So I was wondering if we could get that info from DNF somehow.

**Comment by ignatenkobrain** [comment]
No, it does not work with modules. Well, you can use DNF API to do same, however once you will want to do something more advanced, you will miserably fail :)

**Comment by asamalik** [comment]
Do you know how? All I need is to get a list of the packages that would get installed — ideally as a list of the appropriate objects DNF uses ([I get the list here in the code](https://github.com/minimization/feedback-pipeline/blob/master/rpm_showme.py#L172)).

**Comment by tdawson** [comment]
One thing to keep in mind is that sometimes the rpm size, and the installed size are very different.  Case in point is mozjs60.  The rpm size is 6M.  But the installed size (for x86_64) is 30M.
I know it's possible to check for that in dnf, I just want to make sure that we do.

**Comment by asamalik** [comment]
@tdawson yes, that's right. I'm showing the install size in the reports (or at least I believe I do!).

**Comment by Conan-Kudo** [comment]
@asamalik Have you tried setting DNF to use transaction test mode instead of actually doing it? That should be sufficient for doing space calculations, since you don't care about script execution.

**Comment by asamalik** [comment]
After a great discussion with @tdawson and help from @j-mracek, I've put together the following code as an example to get all the data we need without actually installing anything. Thanks to both of you!

(The code itself is not elegant, but worth recording here for reference.)

```
#!/usr/bin/python3

import sys
import dnf


# Configuration
pkgs_to_install = {'httpd'}
installroot = '/installroot'
releasever = "31"



base = dnf.Base()

base.conf.substitutions['releasever'] = releasever
base.conf.installroot = installroot

base.read_all_repos()
base.fill_sack(load_system_repo=False)

for ftr_spec in pkgs_to_install:
    try:
        base.install(ftr_spec)
    except dnf.exceptions.MarkingError:
        sys.exit('Feature(s) cannot be found: ' + ftr_spec)

try:
    base.resolve()
except dnf.exceptions.DepsolveError:
    sys.exit('Dependencies cannot be resolved.')

query = base.sack.query().filterm(pkg=base.transaction.install_set)
installed = query.filter()

for pkg in installed:
    print("===============")
    print(pkg.name)
    print(pkg.size)
    
    print("")
    
    print("requires:")
    for req in pkg.requires:
        print(" -> " + str(req))
        
    print("")
    print("package dependencies:")
    
    deps = query.filter(provides=pkg.requires)
    
    for dep in deps:
        print(" => " + dep.name)
        
    print("")
    print("")
```

**Comment by j-mracek** [comment]
> After a great discussion with @tdawson and help from @j-mracek, I've put together the following code as an example to get all the data we need without actually installing anything. Thanks to both of you!
> 
> (The code itself is not elegant, but worth recording here for reference.)
> 
> ```
> #!/usr/bin/python3
> 
> import sys
> import dnf
> 
> 
> # Configuration
> pkgs_to_install = {'httpd'}
> installroot = '/installroot'
> releasever = "31"
> 
> 
> 
> base = dnf.Base()
> 
> base.conf.substitutions['releasever'] = releasever
> base.conf.installroot = installroot
> 
> base.read_all_repos()
> base.fill_sack(load_system_repo=False)
> 
> for ftr_spec in pkgs_to_install:
>     try:
>         base.install(ftr_spec)
>     except dnf.exceptions.MarkingError:
>         sys.exit('Feature(s) cannot be found: ' + ftr_spec)
> 
> try:
>     base.resolve()
> except dnf.exceptions.DepsolveError:
>     sys.exit('Dependencies cannot be resolved.')
I do recommend to print an error from depsolver. It makes debugging possible.
> 
> query = base.sack.query().filterm(pkg=base.transaction.install_set)
> installed = query.filter()
Remove ` installed = query.filter()` as unneeded
> 
> for pkg in installed:
replace by `for pkg in query:`
>     print("===============")
>     print(pkg.name)
>     print(pkg.size)
>     
>     print("")
>     
>     print("requires:")
>     for req in pkg.requires:
>         print(" -> " + str(req))
>         
>     print("")
>     print("package dependencies:")
>     
>     deps = query.filter(provides=pkg.requires)
>     
>     for dep in deps:
>         print(" => " + dep.name)
>         
>     print("")
>     print("")
> ```

Also the script does not handle weak deps.

**Comment by asamalik** [comment]
@j-mracek Thanks for the tips!

I know this example doesn't include weak deps, for that I'd add:

```
        print("requires:")
        for req in pkg.requires:
            print(" -> " + str(req))

        print("recommends:")
        for req in pkg.recommends:
            print(" -> " + str(req))

        print("suggests:")
        for req in pkg.suggests:
            print(" -> " + str(req))

        print("package requires:")
        deps = query.filter(provides=pkg.requires)
        for dep in deps:
            print(" => " + dep.name)

        print("package recommends:")
        deps = query.filter(provides=pkg.recommends)
        for dep in deps:
            print(" => " + dep.name)

        print("package suggests:")
        deps = query.filter(provides=pkg.suggests)
        for dep in deps:
            print(" => " + dep.name)
```

**Comment by asamalik** [comment]
@j-mracek Would you have a suggestion on how to emulate layering? Let me explain.

Let's use containers as an example. I have two layers:

1. base image
2. application

Let's say I want to install the following package set to create the base image:

```
glibc-minimal-langpack
coreutils-single
microdnf
```

And the  application would add:

```
httpd
```

I could just merge those lists and do an installation. But what if I need to install the first set **without** weak dependencies, and then layer the second set **with** weak dependencies?

I tried to do the following:

```
base = dnf.Base()
base.conf.installroot = '/installroot'

base.read_all_repos()
base.fill_sack(load_system_repo=False)

# Base image
base.conf.install_weak_deps = False
pkgs_to_install = {'glibc-minimal-langpack', 'coreutils-single', 'microdnf'}

for ftr_spec in pkgs_to_install:
    base.install(ftr_spec)

base.resolve()

# Application
base.conf.install_weak_deps = True
pkgs_to_install = {'httpd'}

for ftr_spec in pkgs_to_install:
    base.install(ftr_spec)

base.resolve()

query = base.sack.query().filterm(pkg=base.transaction.install_set)
```

But weak dependencies for the Base Image got pulled in. But I only want weak dependencies for the Application to be pulled in. Is there a trick for this? Or am I out of luck?

**Comment by asamalik** [comment]
Basically, I want to know the result of this:

```
$ dnf --setopt=install_weak_deps=False --installroot=/installroot --releasever 31 install glibc-minimal-langpack coreutils-single microdnf
$ dnf --installroot=/installroot --releasever 31 install httpd
```

**Comment by j-mracek** [comment]
First of all, weak deps cannot be turned on only for certain set of packages. 
You can try:

```
base.conf.install_weak_deps = True
base.resolve()
install_set_with_weak = base.transaction.install_set

base.conf.install_weak_deps = False
base.resolve()
install_set_without_weak = base.transaction.install_set
```

**Comment by asamalik** [comment]
@j-mracek OK, thanks for the confirmation.

Is there maybe a way to fake the installation? So it would write into the RPMDB, but wouldn't download or install any packages?

If not, I'll just make Feedback Pipeline to universally assume that weak deps are always turned off, and ask people to explicitly list all packages they actually need.

**Comment by Conan-Kudo** [comment]
@asamalik Set the test transaction flag, then it'll do "full" resolution without doing anything.

**Comment by asamalik** [comment]
@Conan-Kudo Do you mean something like:

```
base.conf.tsflags = ['RPMTRANS_FLAG_TEST']
...
base.do_transaction()
```

I tried that before, but it keeps complaining about packages not being downloaded. :(

```
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/dnf/updates-7fc4c739b3909d9f/packages/audit-libs-3.0-0.15.20191104git1c2f876.fc31.x86_64.rpm'
```

**Comment by j-mracek** [comment]
No, it doesn't work like that.
1. incorrect tsflag
```
base.conf.tsflags = ['test']
```
2. It always requires download. 

The important question is what do you want to perform by `So it would write into the RPMDB`? If you do not need to install something simply do not install it. If you want to check file conflicts you have to download required rpms and perform do_transaction with `'test'` flag.

**Comment by asamalik** [comment]
@j-mracek all right, that makes sense.

My motivation with Feedback Pipeline is to build a monitoring service — that just reports how would things look like.

So when I want to have two layers, I want to replicate, for example, what a Fedora Container Base would look like — that is created without weak dependencies. And then, a user can install httpd on top of it, including weak deps — and I want to see how that would look like.

I know I'm taking a tool that exists to install packages, and using it not to install packages. And that's proving to be tricky, which is totally fine. So I'm trying to find different ways to achieve what I want — be able to monitor what real stuff would look like.

So in my RPMDB thought experiment, I thought I could resolve the base image without weak deps, write it down to RPMDB, and then run a second installation on top of that, this time with weak deps. Maybe that's not the best way to do things, but it could work. But maybe there's a better way :)

**Comment by j-mracek** [comment]
I do not recommend to hack rpmdb. I would recommend to create two transaction and then compare base.

like:
```
base.conf.install_weak_deps = True
base.resolve()
install_set_with_weak = set(base.transaction.install_set)

base.conf.install_weak_deps = False
base.resolve()
install_set_without_weak = set(base.transaction.install_set)

difference = install_set_with_weak.difference(install_set_without_weak)
#  or any other python set operation
```

**Comment by asamalik** [comment]
@j-mracek From your example, what would solve my problem is taking the `install_set_with_weak` package set and saving it, somehow, to the second transaction as installed packages.

It's like `base.fill_sack(load_system_repo=True)`, just using the `install_set_with_weak` instead what's actually on the system.

Is that possible?

**Comment by j-mracek** [comment]
No, but you can do something else.
```
base.conf.install_weak_deps = True
base.resolve()
install_set_with_weak = set(base.transaction.install_set)
base.reset(goal=True)
for pkg in install_set_with_weak:
    base.package_install(pkg)
#  then base.install(ftr_spec) as you need or base.conf.install_weak_deps =

base.resolve()
new_set = set(base.transaction.install_set)
additional_packages = new_set - install_set_with_weak
```
But weak deps will be added for all packages anyway.
Steel think that you try or request something that is not logical.

**Comment by asamalik** [comment]
It's all about the "what if" question, and giving it an answer fast.

Two questions, in fact:

**Question 1: How would Fedora images look like if we rebuild them right now, with a fresh content?**

Fedora ships bunch of images, all built without weak deps automatically pulled in. And I want to be able to ask, at any point in time, "if I rebuild these images with new, updated packages, what would be the result?" And I want to know that without actually rebuilding them, because that takes time.

That's very useful to know for the [Minimization objective](https://tiny.distro.builders/views.html). It helps us detect sudden growth quickly, for example.

**Question 2: How would it look like for our users if they got those new images and installed their stuff on top of it?**

This is what makes it complicated.

Fedora users download the Fedora images, and use them for their stuff. Let's say, they take the container base image, and install httpd on top of it using the `dnf install httpd` command. That command pulls in weak deps for httpd and all the other packages that are getting installed in this transaction.

I want to monitor this use case for Minimization, too. Again, to detect sudden growth early enough, perhaps before actually shipping it.

And to make the prediction accurate, I need to do those two distinct steps:

1. Resolve the base image without weak deps
2. Add stuff on top of it with weak deps

...

Answering question No. 1 is easy. I just get the package set, resolve it without weak deps, done.

But answering question No. 2 is trickier then it seems initially. Especially in the example I've given above. That's why I'm trying to figure out this weird layering and combining no weak "deps for some" packages, and "yes weak deps" for other. To be able to predict how that would look like.

...

I know DNF is not a complex prediction tool. It's but a package manager — and quite a good one!

Sorry @j-mracek if I'm confusing you with my crazy questions. I really appreciate you keep answering those! :D 

And I'm not trying to request new DNF functionality, just trying to understand it more to see if I can use it to get my answers quickly and reliably.

**Comment by asamalik** [comment]
Anyway, my compromise solution is the following:

```
# Base image
base = dnf.Base()
base.conf.installroot = '/installroot'
base.conf.tsflags = ['justdb']
base.read_all_repos()
base.fill_sack(load_system_repo=False)

base.conf.install_weak_deps = False
pkgs_to_install = {'glibc-minimal-langpack', 'coreutils-single'}

for ftr_spec in pkgs_to_install:
    base.install(ftr_spec)

base.resolve()
base.download_packages(base.transaction.install_set)
base.do_transaction()

# Application
base = dnf.Base()
base.conf.installroot = '/installroot'
base.read_all_repos()
base.fill_sack(load_system_repo=True)

base.conf.install_weak_deps = True
pkgs_to_install = {'httpd'}

for ftr_spec in pkgs_to_install:
    base.install(ftr_spec)

base.resolve()

query_base = base.sack.query()
base_installed = set(query_base.installed())
use_case_installed = set(base.transaction.install_set)
all_installed = set.union(base_installed, use_case_installed)

all_pkgs = set.union(base.transaction.install_set, base.installed())
query = base.sack.query().filterm(pkg=all_pkgs)
```

`query` now has all the packages I'm interested in. It basically shows the ["Apache httpd on Minimal Base 2" column in Feedback Pipeline](https://tiny.distro.builders/report-by-use-case--httpd--31.html).

The disadvantage of this approach is that it needs to download the "base" images. But that's not too bad. And it's *so* much faster than what we have now.

I'll go forward with this, and we can always optimise it further.

**Comment by asamalik** [comment]
And because I'm not installing anything (not running any scriptlets or other code of the packages), I can easily do any architecture with:

```
base.conf.arch = 'aarch64'
base.conf.ignorearch = True
```

So we can finally do multiarch!

**Comment by j-mracek** [comment]
To help you with Question 2 (how to fake installed content), I see only two options. The first is to fake rpmdb content using rpm API. But it requires to create all requirements and provides of that package. Or play with an internals of libsolv.
