### ISSUE TITLE
Fix sorting in the Views section

### ISSUE THREAD

**Issue by asamalik** [minimization/feedback-pipeline#6]
The [Views section](https://minimization.github.io/reports/view--use-cases-on-bases.html) has many items, currently in a random sort, which makes it hard to use. Let's make it sorted alphabetically.

**Comment by uchu-kitagawa** [comment]
Can I work on this issue?
Also, should I install "fedora: 30" to run this project locally?

**Comment by asamalik** [comment]
@uchu-kitagawa Sure! Just assign the issue to yourself so other people see it's being worked on, and go ahead.

I've just added instructions to the README to how to run a local preview. Fedora is ideal, but it will also run whenever Python is.

Let me know if you have any questions.

**Comment by uchu-kitagawa** [comment]
Thank you for updating README.
But, I couldn't assign the issue to myself because "Assignees" is inactive.
Could you tell me if I need any authority?
I'm sorry I'm a beginner on GitHub.

**Comment by asamalik** [comment]
@uchu-kitagawa Oh, I haven't realised you might need permissions for that — so I have assigned you.

No worries, all of us have been beginners at some point! :)

I see you've already created a fork where you're going to do the changes. Let me know if you need any more help.

**Comment by uchu-kitagawa** [comment]
Thank you for assigning me this issue.
I will do my best to contribute!

I built the environment with option 3.
(My environment：Windows10, VirtualBox, vagrant, CentOS, Docker)

When I ran "devel_feedback_pipeline.py", the log "Generating reports: Bases by releases" was successfully output.
But the screen(html) was not displayed on my host OS browser by URL"http://localhost:8080/".
Could you tell me if you know this cause?

**Comment by asamalik** [comment]
The script in this repository will not start a web server for you that would make it available on that URL. You'll need to open the html files in the output directory in a web browser as files.

**Comment by uchu-kitagawa** [comment]
Thank you for answering my question.
I could see the modified html files in the output directory in a web browser.
I modified the source programs and sent a Pull request.
Please check the changes.

**Comment by asamalik** [comment]
Thank you so much for the PR! [I have replied in the PR](https://github.com/minimization/feedback-pipeline/pull/7), suggesting a little change to make the sorting more predictable.

**Comment by uchu-kitagawa** [comment]
Thank you so much for your good suggestion.
I have sent a PR again.

**Comment by asamalik** [comment]
The [new PR](https://github.com/minimization/feedback-pipeline/pull/8) looks good! Merged. Thank you so much!
